name: Daily

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      checks: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: pnpm
        run: pnpm i --frozen-lockfile
      - name: test
        run: |
          echo repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs
          gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs
          gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs | jq -r '.check_runs[]
          RUN_ID=$(gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs | jq -r '.check_runs[] | select(.name == "Daily") | .html_url | capture("/runs/(?<number>[0-9]+)/jobs") | .number' | sed 's/"//g' | head -n 1)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: last-login
          path: ./last-login.json
          run-id:
            $(gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs | jq -r
            '.check_runs[] | select(.name == "Daily") | .html_url |
            capture("/runs/(?<number>[0-9]+)/jobs") | .number' | sed 's/"//g' |
            head -n 1)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check
        if: always()
        id: check
        run: pnpm check
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          SLACK_USER_TOKEN: ${{secrets.SLACK_USER_TOKEN}}
          SLACK_CHANNEL_NAME: ${{secrets.SLACK_CHANNEL_NAME}}
          CRYPT_PASS: ${{secrets.CRYPT_PASS}}
          CRYPT_SALT: ${{secrets.CRYPT_SALT}}
      - name: Upload Artifact
        if: always() # if: steps.check.outputs.result == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: last-login
          path: last-login.json
          retention-days: 90
