name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: pnpm
        run: pnpm i --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          name: last-login
          path: ./last-login.json
      - name: check
        if: always()
        id: check
        run: pnpm check
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          SLACK_USER_TOKEN: ${{secrets.SLACK_USER_TOKEN}}
          SLACK_CHANNEL_NAME: ${{secrets.SLACK_CHANNEL_NAME}}
          CRYPT_PASS: ${{secrets.CRYPT_PASS}}
          CRYPT_SALT: ${{secrets.CRYPT_SALT}}
      - name: Upload Artifact
        if: always() # if: steps.check.outputs.result == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: last-login
          path: last-login.json
          retention-days: 90
