name: Daily

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: pnpm
        run: pnpm i --frozen-lockfile
      - name: lint
        run: pnpm check
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          SLACK_USER_TOKEN: ${{secrets.SLACK_USER_TOKEN}}
          SLACK_CHANNEL_NAME: ${{secrets.SLACK_CHANNEL_NAME}}
          CRYPT_PASS: ${{secrets.CRYPT_PASS}}
          CRYPT_SALT: ${{secrets.CRYPT_SALT}}
